CREATE TABLE submissions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  T REAL NOT NULL,
  S REAL NOT NULL,
  C REAL NOT NULL,
  E REAL NOT NULL,
  ON_ REAL NOT NULL,
  U REAL NOT NULL,
  SK REAL NOT NULL,
  VT REAL NOT NULL,
  CO REAL NOT NULL,
  A REAL NOT NULL,
  EP REAL NOT NULL,
  D REAL NOT NULL,
  B REAL NOT NULL
);
